// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.API.Catalog.Infrastructure;

namespace Service.API.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20210318073042_AddMoreSampleProductsToCatalogDb")]
    partial class AddMoreSampleProductsToCatalogDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("App.Support.Common.Models.CatalogService.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "5beff28e-bba2-4b1b-9f06-126d6365d4cf",
                            Code = "MP",
                            Name = "Meat & Poultry"
                        },
                        new
                        {
                            Id = "fd6055d7-08a3-4351-8195-7da47e50f028",
                            Code = "FV",
                            Name = "Fruit & Vegetables"
                        },
                        new
                        {
                            Id = "737c9710-e069-436a-a236-660e8277dedf",
                            Code = "DR",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = "bae52764-af07-4043-8586-52816594ee86",
                            Code = "CD",
                            Name = "Confectionary & Desserts"
                        },
                        new
                        {
                            Id = "3786f39a-a229-4689-aed7-d851082cd87a",
                            Code = "CI",
                            Name = "Baking/Cooking Ingredients"
                        },
                        new
                        {
                            Id = "b5901197-4899-4a22-ad39-7f1f4cdcb84b",
                            Code = "MI",
                            Name = "Miscellaneous Items"
                        });
                });

            modelBuilder.Entity("App.Support.Common.Models.CatalogService.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPriceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Packaging")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceUnit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "48d5553e-a450-4523-a143-73263766b62b",
                            CategoryId = "5beff28e-bba2-4b1b-9f06-126d6365d4cf",
                            InventoryQuantity = 12,
                            Name = "Chicken Fillets",
                            Packaging = "6 x 100g",
                            PriceUnit = "GBP",
                            PriceValue = 4.50m,
                            Sku = "MP-000001"
                        },
                        new
                        {
                            Id = "e547f80c-55ff-4541-81e7-d84f55cfdae2",
                            CategoryId = "5beff28e-bba2-4b1b-9f06-126d6365d4cf",
                            InventoryQuantity = 6,
                            Name = "Sirloin Steaks",
                            Packaging = "4 x 6-8oz",
                            PriceUnit = "GBP",
                            PriceValue = 45.70m,
                            Sku = "MP-000002"
                        },
                        new
                        {
                            Id = "74ae8b23-2e53-4fb2-a4a8-143a79d7c3a5",
                            CategoryId = "5beff28e-bba2-4b1b-9f06-126d6365d4cf",
                            InventoryQuantity = 8,
                            Name = "Whole Free-Range Turkey",
                            OldPriceValue = 48.25m,
                            Packaging = "1 x 16-18lbs",
                            PriceUnit = "GBP",
                            PriceValue = 43.20m,
                            Sku = "MP-000003"
                        },
                        new
                        {
                            Id = "cab06749-c2ed-4671-992a-939f95dc41e6",
                            CategoryId = "fd6055d7-08a3-4351-8195-7da47e50f028",
                            InventoryQuantity = 0,
                            Name = "Granny Smith Apples",
                            Packaging = "4 x 16 each",
                            PriceUnit = "GBP",
                            PriceValue = 3.75m,
                            Sku = "FV-000002"
                        },
                        new
                        {
                            Id = "b81fe919-e701-4f11-b776-c57eda4cb321",
                            CategoryId = "fd6055d7-08a3-4351-8195-7da47e50f028",
                            InventoryQuantity = 2,
                            Name = "Loose Carrots",
                            Packaging = "4 x 20 each",
                            PriceUnit = "GBP",
                            PriceValue = 2.67m,
                            Sku = "FV-000003"
                        },
                        new
                        {
                            Id = "a1821ad4-1821-4080-ae73-93359d9df11e",
                            CategoryId = "fd6055d7-08a3-4351-8195-7da47e50f028",
                            InventoryQuantity = 8,
                            Name = "Mandarin Oranges",
                            Packaging = "6 x 10 x 12",
                            PriceUnit = "GBP",
                            PriceValue = 12.23m,
                            Sku = "FV-000004"
                        },
                        new
                        {
                            Id = "34f98921-e46a-4937-872b-e2c57e705f3f",
                            CategoryId = "fd6055d7-08a3-4351-8195-7da47e50f028",
                            InventoryQuantity = 5,
                            Name = "Cauliflower Florets",
                            OldPriceValue = 6.75m,
                            Packaging = "10 x 500g",
                            PriceUnit = "GBP",
                            PriceValue = 5.00m,
                            Sku = "FV-000001"
                        },
                        new
                        {
                            Id = "77e63e97-b41a-4882-9574-52a3738fd93f",
                            CategoryId = "737c9710-e069-436a-a236-660e8277dedf",
                            InventoryQuantity = 6,
                            Name = "Coca-Cola",
                            OldPriceValue = 8.50m,
                            Packaging = "6 x 2L",
                            PriceUnit = "GBP",
                            PriceValue = 8.30m,
                            Sku = "DR-000001"
                        },
                        new
                        {
                            Id = "d2fb685f-86dd-47ac-bb23-8ffd8ce84941",
                            CategoryId = "737c9710-e069-436a-a236-660e8277dedf",
                            InventoryQuantity = 9,
                            Name = "Still Mineral Water",
                            Packaging = "6 x 24 x 500ml",
                            PriceUnit = "GBP",
                            PriceValue = 21.75m,
                            Sku = "DR-000002"
                        },
                        new
                        {
                            Id = "bf7b5f89-a569-4e3d-acb8-04a07e1e1130",
                            CategoryId = "737c9710-e069-436a-a236-660e8277dedf",
                            InventoryQuantity = 16,
                            Name = "Sparkling Mineral Water",
                            Packaging = "6 x 24 x 500ml",
                            PriceUnit = "GBP",
                            PriceValue = 25.83m,
                            Sku = "DR-000003"
                        },
                        new
                        {
                            Id = "8a7af7e8-b644-4abe-aea7-bd869f116d8b",
                            CategoryId = "bae52764-af07-4043-8586-52816594ee86",
                            InventoryQuantity = 4,
                            Name = "Mars Bar",
                            Packaging = "6 x 24 x 50g",
                            PriceUnit = "GBP",
                            PriceValue = 42.82m,
                            Sku = "CD-000001"
                        },
                        new
                        {
                            Id = "f761a566-37b6-43a2-84cb-e9a36ab42f33",
                            CategoryId = "bae52764-af07-4043-8586-52816594ee86",
                            InventoryQuantity = 6,
                            Name = "Peppermint Chewing Gum",
                            Packaging = "6 x 50 x 30g",
                            PriceUnit = "GBP",
                            PriceValue = 35.70m,
                            Sku = "CD-000002"
                        },
                        new
                        {
                            Id = "16aab369-9e83-49a4-9832-f85b295c58f6",
                            CategoryId = "bae52764-af07-4043-8586-52816594ee86",
                            InventoryQuantity = 0,
                            Name = "Strawberry Cheesecake,",
                            Packaging = "4 x 12 portions",
                            PriceUnit = "GBP",
                            PriceValue = 8.52m,
                            Sku = "CD-000003"
                        },
                        new
                        {
                            Id = "00f5a6e8-7440-44ae-af92-3e3f04e5ca9d",
                            CategoryId = "bae52764-af07-4043-8586-52816594ee86",
                            InventoryQuantity = 2,
                            Name = "Vanilla Ice Cream",
                            Packaging = "6 x 4L",
                            PriceUnit = "GBP",
                            PriceValue = 3.80m,
                            Sku = "CD-000004"
                        },
                        new
                        {
                            Id = "5e0b02d5-a25f-4617-9215-3c646f9b4ae8",
                            CategoryId = "3786f39a-a229-4689-aed7-d851082cd87a",
                            InventoryQuantity = 4,
                            Name = "Plain Flour",
                            Packaging = "10 x 1kg",
                            PriceUnit = "GBP",
                            PriceValue = 6.21m,
                            Sku = "CI-000001"
                        },
                        new
                        {
                            Id = "b0ad84dc-1df9-4e84-970e-d6e49dee87f3",
                            CategoryId = "3786f39a-a229-4689-aed7-d851082cd87a",
                            InventoryQuantity = 6,
                            Name = "Icing Sugar",
                            Packaging = "12 x 500g",
                            PriceUnit = "GBP",
                            PriceValue = 9.38m,
                            Sku = "CI-000002"
                        },
                        new
                        {
                            Id = "89090eed-5f8d-44bd-ac60-af45256c92ec",
                            CategoryId = "3786f39a-a229-4689-aed7-d851082cd87a",
                            InventoryQuantity = 9,
                            Name = "Free-Range Eggs",
                            Packaging = "10 x 12 each",
                            PriceUnit = "GBP",
                            PriceValue = 9.52m,
                            Sku = "CI-000003"
                        },
                        new
                        {
                            Id = "e337af6b-c746-4d04-9dac-f57cc52a6158",
                            CategoryId = "3786f39a-a229-4689-aed7-d851082cd87a",
                            InventoryQuantity = 13,
                            Name = "Caster Sugar",
                            Packaging = "16 x 750g",
                            PriceUnit = "GBP",
                            PriceValue = 12.76m,
                            Sku = "CI-000004"
                        },
                        new
                        {
                            Id = "3a8af515-a1cc-454a-99f2-fcdaef554d6c",
                            CategoryId = "b5901197-4899-4a22-ad39-7f1f4cdcb84b",
                            InventoryQuantity = 19,
                            Name = "Kitchen Roll",
                            Packaging = "100 x 300 sheets",
                            PriceUnit = "GBP",
                            PriceValue = 43.92m,
                            Sku = "MI-000001"
                        },
                        new
                        {
                            Id = "4bc78c44-14c7-46a5-a877-12debfdd65b5",
                            CategoryId = "b5901197-4899-4a22-ad39-7f1f4cdcb84b",
                            InventoryQuantity = 7,
                            Name = "Paper Plates",
                            Packaging = "10 x 200 each",
                            PriceUnit = "GBP",
                            PriceValue = 16.19m,
                            Sku = "MI-000002"
                        });
                });

            modelBuilder.Entity("App.Support.Common.Models.CatalogService.Product", b =>
                {
                    b.HasOne("App.Support.Common.Models.CatalogService.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
