// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.API.Catalog.Infrastructure;

namespace Service.API.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20210314120309_CreateAndSeedCategories")]
    partial class CreateAndSeedCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("App.Support.Common.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "9580adac-4659-4ff8-8061-b47f825ea98b",
                            Code = "MP",
                            Name = "Meat & Poultry"
                        },
                        new
                        {
                            Id = "321d66d0-6fc7-4fbe-9c2c-9d8e15c9e328",
                            Code = "FV",
                            Name = "Fruit & Vegetables"
                        },
                        new
                        {
                            Id = "01e6e9e1-67df-4f72-96b8-7cc95f0f40bd",
                            Code = "DR",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = "fe60ab82-1f5b-431b-b0af-193a4893ae9c",
                            Code = "CD",
                            Name = "Confectionary & Desserts"
                        },
                        new
                        {
                            Id = "5892511d-746f-407f-92b1-9421bd91ad10",
                            Code = "CI",
                            Name = "Baking/Cooking Ingredients"
                        },
                        new
                        {
                            Id = "788695dc-8187-460c-80c9-037b001f1147",
                            Code = "MI",
                            Name = "Miscellaneous Items"
                        });
                });

            modelBuilder.Entity("App.Support.Common.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Packaging")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("App.Support.Common.Models.Product", b =>
                {
                    b.HasOne("App.Support.Common.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
